//
//  GymPrecompiled.swift
//  MyFirstProject
//
//  Created by Federica Mosca on 22/04/23.
//

import Foundation

let GymWiki: [Exercise] = [
    Exercise(name: "Cable Chest Flys", muscle: .chest, description: "Set both pulleys directly at (or slightly above) shoulder height and select the desired weight.Grasp both handles with a neutral grip and take a step forward to split the stance.Press the handles to lockout while flexing the pecs and extending the elbows.\n4) Return to the starting position by flexing your pecs and bringing the handles together at chest height."),
        Exercise(name: "Bench Press", muscle: .chest, description: "Place your feet in provided stirrups. Hold the weight directly over the shoulders, arms slightly wider than shoulder height.Push the weight up until your arms are angled at 45 degrees at the top.Slowly lower the weight back down to chest height, elbows out to the sides."),
        Exercise(name: "T-Bar Row", muscle: .back, description: "Place the end of an empty barbell into the corner of a room.Load the opposite end of the bar with plates and straddle it.Bend over at the hips until your torso is about a 45-degree angle to the floor with arms extended. Hook a V-grip handle (the kind you see at a cable station) under the bar and hold with both hands. Keeping your lower back in its natural arch, squeeze your shoulder blades together and pull the bar until the plates touch your chest."),
        Exercise(name: "Wide Grip Seated Row", muscle: .back, description: "Lean forward slightly in the starting position, and lean back slightly in the end position. Let your scapulae move freely by letting them slide forward in the starting position, and pull them back in the end position.Cable rows can be done with a wide or close grip, and most people find that they get better contact with their biceps with the close grip, and better contact with their back muscles with the wide grip."),
        Exercise(name: "Dumbbell Lateral Raise", muscle: .shoulders, description: "Lifting laterally activates your posterior deltoids and upper-back muscles. Standing, hold dumbbells with your palms facing each other. Keeping your elbows and knees slightly bent, raise your arms out from your sides in wide arcs to about shoulder level. Slowly return to the starting position." ),
        Exercise(name: "Seated Military Press", muscle: .shoulders, description: "Along with building anterior, medial and rear deltoid strength, this exercise also targets the upper back. Sitting, hold a dumbbell in each hand, and raise both weights to shoulder level with palms facing out and elbows bent. Press the weights up and toward each other as you straighten your arms. At the top of the movement, keep a slight bend in your elbows. Slowly bring down the weights, and return to the starting position."),
        Exercise(name: "Barbell Curl", muscle: .biceps, description: "Grab a barbell with an underhand grip, slightly wider than the shoulders. Pull your shoulders back into their sockets to expose the fronts of your biceps. Your elbows should be under your shoulder joints, or slightly in front by your ribs. Curl the barbell up using your biceps." ),
        Exercise(name: "Hammer Curl", muscle: .biceps, description: "Hold a dumbbell in each hand while standing. Turn your wrists so that they’re facing each other. Keep your arms tucked in at your sides and flex your elbows to curl the dumbbells up towards your shoulders. Lower them back down with control." ),
        Exercise(name: "Cable Push Down", muscle: .triceps, description: "Start by bracing your abdominals. Tuck your elbows in at your sides and position your feet slightly apart. Inhale. Push down until your elbows are fully extended but not yet in the straight, locked position. Keep your elbows close to your body and bend your knees slightly on the pushdown. Resist bending forward. Try to keep your back as straight as possible as you push down. As you exhale, return to the starting point using a controlled movement. Try not to crash the weights"),
        Exercise(name: "Cable Overhead Extension With Rope", muscle: .triceps, description: "Attach a rope to a cable stack as high as possible and assume a standing position. Utilize a split stance, grasp the rope overhead with a neutral grip (palms facing), and lean forward by hinging at the hips. Initiate the movement by extending the elbows and flexing the triceps. Pull the rope downward until the elbows are almost locked out and then slowly lower under control back to the starting position. Repeat for the desired number of repetitions."),
        Exercise(name: "Leg Press", muscle: .quads, description: "Brace your abdominal muscles and push the platform away with your heels and forefoot. Your heels should remain flat on the footplate. The front of your foot or toes should never be used exclusively to move the pad forward. While exhaling, extend your legs and keep your head and back flat against the seat pad. Extend with slow control rather than with an explosive movement. Pause at the top of the movement. Do not lock out your knees, and ensure that they are not bowing out or in. While inhaling, return the footplate to the starting position by gradually bending the knees. Keep the feet and back flat throughout. If you have never done leg presses, start modestly with three sets of 10 leg presses. You can advance from there as you build strength"),
        Exercise(name: "Leg Extension", muscle: .quads, description: "Place your hands on the hand bars. Lift the weight while exhaling until your legs are almost straight. Do not lock your knees. Keep your back against the backrest and do not arch your back. Exhale and lower the weight back to starting position."),
        Exercise(name: "Barbell Hip Thrust", muscle: .glutes, description: "Rest your upper back on a bench and sit on the floor with legs extended. Roll a loaded barbell up your thighs until the bar sits on your lap (you may want to place a towel or mat on your hips or attach a pad to the bar for comfort). Brace your abs and drive your heels into the floor to extend your hips, raising them until your thighs and upper body are parallel to the floor. "),
        Exercise(name: "Sumo Romanian Deadlift", muscle: .glutes, description: "Stand with your feet outside shoulder-width and toes turned out about 15 degrees. Bend your hips back and let your knees bend as needed until you can grasp the bar at shoulder-width. Keeping your lower back in its natural arch, push your hips forward to raise the bar to lockout. To begin each subsequent rep, push your hips back and lower the bar to mid-shin level. Do not bend your knees more and make it a deadlift—the movement must come almost entirely from your hips."),
        Exercise(name: "Deadlift", muscle: .hamstrings, description: "With feet shoulder-width apart and arms just outside of the legs, push the hips back as far as possible then bend the knee far enough to reach the bar. Keeping your core tight and your spine as tall as possible, pull the bar from the ground by standing tall and pulling the hips back to your standing position. Slowly lower the bar back to the ground, pushing your hips back as you do."),
        Exercise(name: "Hex/Trap Bar Deadlift", muscle: .hamstrings, description: "Lower your body down to grab the high handles of the hex bar with feet shoulder-width apart. Keeping your core tight and your shoulders above your hips, extend your knees and hips to stand up. Your upper body should remain as relaxed as possible while maintaining a firm grip on the bar. Squeeze your glutes at the top. Slowly lower the bar to the ground, pushing your butt back as you do."),
        Exercise(name: "Leg Press", muscle: .calves, description: "Sit at the leg press machine in a manner where just the top part of each foot is touching the bottom of the platform in front of you. Push back as far as you can while keeping your toes connected to the platform. Return and repeat"),
        Exercise(name: "Seated Calf Raise", muscle: .calves, description: "Sit at the leg press machine in a manner where just the top part of each foot is touching the bottom of the platform in front of you. Push back as far as you can while keeping your toes connected to the platform. Return and repeat"),
        Exercise(name: "Leg Raise", muscle: .abdominals, description: "Lie down flat on your back on the ground. Keeping your legs as straight as possible, raise them until they’re vertical or as close as you can get. Lower them and repeat"),
        Exercise(name: "Bicyle Crush", muscle: .abdominals, description: "Lie on your back, extend your legs and hold them just above the ground. Place your fingers lightly on your temples. Bring one knee up towards your chest and twist your torso so that the opposite elbow comes over towards it. Your elbow and knee needn’t touch, but thinking of that connection between the two body parts is a good way to guide the movement of your torso. Lower both your torso and leg at the same time, then repeat on the opposite side.")
]

